export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const GET_USERS = "GET_USERS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_PROFILE = "USER_PROFILE";